//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class GetGPSFixGoal : Message
    {
        public const string k_RosMessageName = "sam_msgs/GetGPSFix";
        public override string RosMessageName => k_RosMessageName;

        public float timeout;
        public uint required_gps_msgs;

        public GetGPSFixGoal()
        {
            this.timeout = 0.0f;
            this.required_gps_msgs = 0;
        }

        public GetGPSFixGoal(float timeout, uint required_gps_msgs)
        {
            this.timeout = timeout;
            this.required_gps_msgs = required_gps_msgs;
        }

        public static GetGPSFixGoal Deserialize(MessageDeserializer deserializer) => new GetGPSFixGoal(deserializer);

        private GetGPSFixGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.timeout);
            deserializer.Read(out this.required_gps_msgs);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timeout);
            serializer.Write(this.required_gps_msgs);
        }

        public override string ToString()
        {
            return "GetGPSFixGoal: " +
            "\ntimeout: " + timeout.ToString() +
            "\nrequired_gps_msgs: " + required_gps_msgs.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
