//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class SystemsCheckGoal : Message
    {
        public const string k_RosMessageName = "sam_msgs/SystemsCheck";
        public override string RosMessageName => k_RosMessageName;


        public SystemsCheckGoal()
        {
        }
        public static SystemsCheckGoal Deserialize(MessageDeserializer deserializer) => new SystemsCheckGoal(deserializer);

        private SystemsCheckGoal(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "SystemsCheckGoal: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
