//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class SystemsCheckFeedback : Message
    {
        public const string k_RosMessageName = "sam_msgs/SystemsCheck";
        public override string RosMessageName => k_RosMessageName;

        public string status;

        public SystemsCheckFeedback()
        {
            this.status = "";
        }

        public SystemsCheckFeedback(string status)
        {
            this.status = status;
        }

        public static SystemsCheckFeedback Deserialize(MessageDeserializer deserializer) => new SystemsCheckFeedback(deserializer);

        private SystemsCheckFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "SystemsCheckFeedback: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
