//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Smarc
{
    [Serializable]
    public class StringStampedMsg : Message
    {
        public const string k_RosMessageName = "smarc_msgs/StringStamped";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg time_sent;
        public BuiltinInterfaces.TimeMsg time_received;
        public string data;

        public StringStampedMsg()
        {
            this.time_sent = new BuiltinInterfaces.TimeMsg();
            this.time_received = new BuiltinInterfaces.TimeMsg();
            this.data = "";
        }

        public StringStampedMsg(BuiltinInterfaces.TimeMsg time_sent, BuiltinInterfaces.TimeMsg time_received, string data)
        {
            this.time_sent = time_sent;
            this.time_received = time_received;
            this.data = data;
        }

        public static StringStampedMsg Deserialize(MessageDeserializer deserializer) => new StringStampedMsg(deserializer);

        private StringStampedMsg(MessageDeserializer deserializer)
        {
            this.time_sent = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.time_received = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time_sent);
            serializer.Write(this.time_received);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "StringStampedMsg: " +
            "\ntime_sent: " + time_sent.ToString() +
            "\ntime_received: " + time_received.ToString() +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
