//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Smarc
{
    [Serializable]
    public class ThrusterDCMsg : Message
    {
        public const string k_RosMessageName = "smarc_msgs/ThrusterDC";
        public override string RosMessageName => k_RosMessageName;

        public float dc;
        //  NOTE: [-1.,1]

        public ThrusterDCMsg()
        {
            this.dc = 0.0f;
        }

        public ThrusterDCMsg(float dc)
        {
            this.dc = dc;
        }

        public static ThrusterDCMsg Deserialize(MessageDeserializer deserializer) => new ThrusterDCMsg(deserializer);

        private ThrusterDCMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.dc);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.dc);
        }

        public override string ToString()
        {
            return "ThrusterDCMsg: " +
            "\ndc: " + dc.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
