//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class UavcanUpdateBatteryRequest : Message
    {
        public const string k_RosMessageName = "sam_msgs/UavcanUpdateBattery";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Update battery
        // 
        public byte node_id;
        public const byte IS_FULL = 1; //  Battery is full right now
        public const byte WAS_FULL = 2; //  Battery was full when Sam started
        public const byte ADD_CHARGE = 3; //  Add enclosed charge
        public const byte ON_MAINS = 4; //  Powered externally
        public byte command;
        public float charge;
        //  Ah (can be negative)

        public UavcanUpdateBatteryRequest()
        {
            this.node_id = 0;
            this.command = 0;
            this.charge = 0.0f;
        }

        public UavcanUpdateBatteryRequest(byte node_id, byte command, float charge)
        {
            this.node_id = node_id;
            this.command = command;
            this.charge = charge;
        }

        public static UavcanUpdateBatteryRequest Deserialize(MessageDeserializer deserializer) => new UavcanUpdateBatteryRequest(deserializer);

        private UavcanUpdateBatteryRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.node_id);
            deserializer.Read(out this.command);
            deserializer.Read(out this.charge);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.node_id);
            serializer.Write(this.command);
            serializer.Write(this.charge);
        }

        public override string ToString()
        {
            return "UavcanUpdateBatteryRequest: " +
            "\nnode_id: " + node_id.ToString() +
            "\ncommand: " + command.ToString() +
            "\ncharge: " + charge.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
