//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class UavcanUpdateBatteryResponse : Message
    {
        public const string k_RosMessageName = "sam_msgs/UavcanUpdateBattery";
        public override string RosMessageName => k_RosMessageName;

        public const byte UPDATE_SUCCESSFULL = 1;
        public const byte UPDATE_FAILED = 0;
        public byte success;

        public UavcanUpdateBatteryResponse()
        {
            this.success = 0;
        }

        public UavcanUpdateBatteryResponse(byte success)
        {
            this.success = success;
        }

        public static UavcanUpdateBatteryResponse Deserialize(MessageDeserializer deserializer) => new UavcanUpdateBatteryResponse(deserializer);

        private UavcanUpdateBatteryResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "UavcanUpdateBatteryResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
