//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class ConsumedChargeArrayMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/ConsumedChargeArray";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Consumed charge array
        // 
        public Std.HeaderMsg header;
        // 
        //  Consumed charge mAh
        // 
        public ConsumedChargeMsg[] array;

        public ConsumedChargeArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.array = new ConsumedChargeMsg[0];
        }

        public ConsumedChargeArrayMsg(Std.HeaderMsg header, ConsumedChargeMsg[] array)
        {
            this.header = header;
            this.array = array;
        }

        public static ConsumedChargeArrayMsg Deserialize(MessageDeserializer deserializer) => new ConsumedChargeArrayMsg(deserializer);

        private ConsumedChargeArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.array, ConsumedChargeMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.array);
            serializer.Write(this.array);
        }

        public override string ToString()
        {
            return "ConsumedChargeArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\narray: " + System.String.Join(", ", array.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
