//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class LightCommandMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/LightCommand";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Light command
        // 
        public ushort id;
        public Std.ColorRGBAMsg command;

        public LightCommandMsg()
        {
            this.id = 0;
            this.command = new Std.ColorRGBAMsg();
        }

        public LightCommandMsg(ushort id, Std.ColorRGBAMsg command)
        {
            this.id = id;
            this.command = command;
        }

        public static LightCommandMsg Deserialize(MessageDeserializer deserializer) => new LightCommandMsg(deserializer);

        private LightCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            this.command = Std.ColorRGBAMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.command);
        }

        public override string ToString()
        {
            return "LightCommandMsg: " +
            "\nid: " + id.ToString() +
            "\ncommand: " + command.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
