//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class ThrusterAnglesMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/ThrusterAngles";
        public override string RosMessageName => k_RosMessageName;

        public float thruster_vertical_radians;
        public float thruster_horizontal_radians;
        public Std.HeaderMsg header;

        public ThrusterAnglesMsg()
        {
            this.thruster_vertical_radians = 0.0f;
            this.thruster_horizontal_radians = 0.0f;
            this.header = new Std.HeaderMsg();
        }

        public ThrusterAnglesMsg(float thruster_vertical_radians, float thruster_horizontal_radians, Std.HeaderMsg header)
        {
            this.thruster_vertical_radians = thruster_vertical_radians;
            this.thruster_horizontal_radians = thruster_horizontal_radians;
            this.header = header;
        }

        public static ThrusterAnglesMsg Deserialize(MessageDeserializer deserializer) => new ThrusterAnglesMsg(deserializer);

        private ThrusterAnglesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.thruster_vertical_radians);
            deserializer.Read(out this.thruster_horizontal_radians);
            this.header = Std.HeaderMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.thruster_vertical_radians);
            serializer.Write(this.thruster_horizontal_radians);
            serializer.Write(this.header);
        }

        public override string ToString()
        {
            return "ThrusterAnglesMsg: " +
            "\nthruster_vertical_radians: " + thruster_vertical_radians.ToString() +
            "\nthruster_horizontal_radians: " + thruster_horizontal_radians.ToString() +
            "\nheader: " + header.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
