//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SaabMsgs
{
    [Serializable]
    public class MPCmsgMsg : Message
    {
        public const string k_RosMessageName = "saab_msgs_pkg/MPCmsg";
        public override string RosMessageName => k_RosMessageName;

        public double f_x;
        public double f_y;
        public double f_z;
        public double t_x;
        public double t_y;
        public double t_z;

        public MPCmsgMsg()
        {
            this.f_x = 0.0;
            this.f_y = 0.0;
            this.f_z = 0.0;
            this.t_x = 0.0;
            this.t_y = 0.0;
            this.t_z = 0.0;
        }

        public MPCmsgMsg(double f_x, double f_y, double f_z, double t_x, double t_y, double t_z)
        {
            this.f_x = f_x;
            this.f_y = f_y;
            this.f_z = f_z;
            this.t_x = t_x;
            this.t_y = t_y;
            this.t_z = t_z;
        }

        public static MPCmsgMsg Deserialize(MessageDeserializer deserializer) => new MPCmsgMsg(deserializer);

        private MPCmsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.f_x);
            deserializer.Read(out this.f_y);
            deserializer.Read(out this.f_z);
            deserializer.Read(out this.t_x);
            deserializer.Read(out this.t_y);
            deserializer.Read(out this.t_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.f_x);
            serializer.Write(this.f_y);
            serializer.Write(this.f_z);
            serializer.Write(this.t_x);
            serializer.Write(this.t_y);
            serializer.Write(this.t_z);
        }

        public override string ToString()
        {
            return "MPCmsgMsg: " +
            "\nf_x: " + f_x.ToString() +
            "\nf_y: " + f_y.ToString() +
            "\nf_z: " + f_z.ToString() +
            "\nt_x: " + t_x.ToString() +
            "\nt_y: " + t_y.ToString() +
            "\nt_z: " + t_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
