//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SaabMsgs
{
    [Serializable]
    public class PosMsg : Message
    {
        public const string k_RosMessageName = "saab_msgs_pkg/Pos";
        public override string RosMessageName => k_RosMessageName;

        public double x;
        public double y;
        public double z;
        public double a_x;
        public double a_y;
        public double a_z;

        public PosMsg()
        {
            this.x = 0.0;
            this.y = 0.0;
            this.z = 0.0;
            this.a_x = 0.0;
            this.a_y = 0.0;
            this.a_z = 0.0;
        }

        public PosMsg(double x, double y, double z, double a_x, double a_y, double a_z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.a_x = a_x;
            this.a_y = a_y;
            this.a_z = a_z;
        }

        public static PosMsg Deserialize(MessageDeserializer deserializer) => new PosMsg(deserializer);

        private PosMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.a_x);
            deserializer.Read(out this.a_y);
            deserializer.Read(out this.a_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.a_x);
            serializer.Write(this.a_y);
            serializer.Write(this.a_z);
        }

        public override string ToString()
        {
            return "PosMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\na_x: " + a_x.ToString() +
            "\na_y: " + a_y.ToString() +
            "\na_z: " + a_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
