//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SmarcMission
{
    [Serializable]
    public class TopicsMsg : Message
    {
        public const string k_RosMessageName = "smarc_mission_msgs/Topics";
        public override string RosMessageName => k_RosMessageName;

        public const string DUBINS_SERVICE = "'mission/dubins_service'";
        public const string UTM_LATLON_CONVERSION_SERVICE = "'mission/utm_latlon_conversion_service'";

        public TopicsMsg()
        {
        }
        public static TopicsMsg Deserialize(MessageDeserializer deserializer) => new TopicsMsg(deserializer);

        private TopicsMsg(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "TopicsMsg: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
