//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Smarc
{
    [Serializable]
    public class ThrusterRPMMsg : Message
    {
        public const string k_RosMessageName = "smarc_msgs/ThrusterRPM";
        public override string RosMessageName => k_RosMessageName;

        public int rpm;
        //  NOTE: can be negative also

        public ThrusterRPMMsg()
        {
            this.rpm = 0;
        }

        public ThrusterRPMMsg(int rpm)
        {
            this.rpm = rpm;
        }

        public static ThrusterRPMMsg Deserialize(MessageDeserializer deserializer) => new ThrusterRPMMsg(deserializer);

        private ThrusterRPMMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.rpm);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.rpm);
        }

        public override string ToString()
        {
            return "ThrusterRPMMsg: " +
            "\nrpm: " + rpm.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
