//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class ArrayCommandMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/ArrayCommand";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Actuator commands.
        //  The system supports up to 256 actuators; up to 15 of them can be commanded with one message.
        // 
        public CommandMsg[] commands;

        public ArrayCommandMsg()
        {
            this.commands = new CommandMsg[0];
        }

        public ArrayCommandMsg(CommandMsg[] commands)
        {
            this.commands = commands;
        }

        public static ArrayCommandMsg Deserialize(MessageDeserializer deserializer) => new ArrayCommandMsg(deserializer);

        private ArrayCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.commands, CommandMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.commands);
            serializer.Write(this.commands);
        }

        public override string ToString()
        {
            return "ArrayCommandMsg: " +
            "\ncommands: " + System.String.Join(", ", commands.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
