//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class CircuitStatusStampedMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/CircuitStatusStamped";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Circuit status with timestamp
        // 
        public Std.HeaderMsg header;
        // 
        //  Uavcan CircuitStatus
        // 
        public CircuitStatusMsg circuit;

        public CircuitStatusStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.circuit = new CircuitStatusMsg();
        }

        public CircuitStatusStampedMsg(Std.HeaderMsg header, CircuitStatusMsg circuit)
        {
            this.header = header;
            this.circuit = circuit;
        }

        public static CircuitStatusStampedMsg Deserialize(MessageDeserializer deserializer) => new CircuitStatusStampedMsg(deserializer);

        private CircuitStatusStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.circuit = CircuitStatusMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.circuit);
        }

        public override string ToString()
        {
            return "CircuitStatusStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\ncircuit: " + circuit.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
