//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class ConsumedChargeMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/ConsumedCharge";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Consumed charge message
        // 
        public Std.HeaderMsg header;
        // 
        //  circuit id
        // 
        public ushort circuit_id;
        // 
        //  Consumed charge mAh
        // 
        public float charge;

        public ConsumedChargeMsg()
        {
            this.header = new Std.HeaderMsg();
            this.circuit_id = 0;
            this.charge = 0.0f;
        }

        public ConsumedChargeMsg(Std.HeaderMsg header, ushort circuit_id, float charge)
        {
            this.header = header;
            this.circuit_id = circuit_id;
            this.charge = charge;
        }

        public static ConsumedChargeMsg Deserialize(MessageDeserializer deserializer) => new ConsumedChargeMsg(deserializer);

        private ConsumedChargeMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.circuit_id);
            deserializer.Read(out this.charge);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.circuit_id);
            serializer.Write(this.charge);
        }

        public override string ToString()
        {
            return "ConsumedChargeMsg: " +
            "\nheader: " + header.ToString() +
            "\ncircuit_id: " + circuit_id.ToString() +
            "\ncharge: " + charge.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
