//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class ThrusterRPMsMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/ThrusterRPMs";
        public override string RosMessageName => k_RosMessageName;

        public int thruster_1_rpm;
        //  NOTE: can be negative also
        public int thruster_2_rpm;
        //  NOTE: can be negative also
        public Std.HeaderMsg header;

        public ThrusterRPMsMsg()
        {
            this.thruster_1_rpm = 0;
            this.thruster_2_rpm = 0;
            this.header = new Std.HeaderMsg();
        }

        public ThrusterRPMsMsg(int thruster_1_rpm, int thruster_2_rpm, Std.HeaderMsg header)
        {
            this.thruster_1_rpm = thruster_1_rpm;
            this.thruster_2_rpm = thruster_2_rpm;
            this.header = header;
        }

        public static ThrusterRPMsMsg Deserialize(MessageDeserializer deserializer) => new ThrusterRPMsMsg(deserializer);

        private ThrusterRPMsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.thruster_1_rpm);
            deserializer.Read(out this.thruster_2_rpm);
            this.header = Std.HeaderMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.thruster_1_rpm);
            serializer.Write(this.thruster_2_rpm);
            serializer.Write(this.header);
        }

        public override string ToString()
        {
            return "ThrusterRPMsMsg: " +
            "\nthruster_1_rpm: " + thruster_1_rpm.ToString() +
            "\nthruster_2_rpm: " + thruster_2_rpm.ToString() +
            "\nheader: " + header.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
