//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class UavcanNodeStatusNamedMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/UavcanNodeStatusNamed";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Node ID
        // 
        public byte id;
        // 
        //  Node name
        // 
        public string name;
        // 
        //  NodeStatus
        // 
        public UavcanNodeStatusMsg ns;

        public UavcanNodeStatusNamedMsg()
        {
            this.id = 0;
            this.name = "";
            this.ns = new UavcanNodeStatusMsg();
        }

        public UavcanNodeStatusNamedMsg(byte id, string name, UavcanNodeStatusMsg ns)
        {
            this.id = id;
            this.name = name;
            this.ns = ns;
        }

        public static UavcanNodeStatusNamedMsg Deserialize(MessageDeserializer deserializer) => new UavcanNodeStatusNamedMsg(deserializer);

        private UavcanNodeStatusNamedMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.name);
            this.ns = UavcanNodeStatusMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.name);
            serializer.Write(this.ns);
        }

        public override string ToString()
        {
            return "UavcanNodeStatusNamedMsg: " +
            "\nid: " + id.ToString() +
            "\nname: " + name.ToString() +
            "\nns: " + ns.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
