//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Geographic
{
    [Serializable]
    public class GeoPoseWithCovarianceStampedMsg : Message
    {
        public const string k_RosMessageName = "geographic_msgs/GeoPoseWithCovarianceStamped";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public GeoPoseWithCovarianceMsg pose;

        public GeoPoseWithCovarianceStampedMsg()
        {
            this.header = new HeaderMsg();
            this.pose = new GeoPoseWithCovarianceMsg();
        }

        public GeoPoseWithCovarianceStampedMsg(HeaderMsg header, GeoPoseWithCovarianceMsg pose)
        {
            this.header = header;
            this.pose = pose;
        }

        public static GeoPoseWithCovarianceStampedMsg Deserialize(MessageDeserializer deserializer) => new GeoPoseWithCovarianceStampedMsg(deserializer);

        private GeoPoseWithCovarianceStampedMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.pose = GeoPoseWithCovarianceMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "GeoPoseWithCovarianceStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
