//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class BallastAnglesMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/BallastAngles";
        public override string RosMessageName => k_RosMessageName;

        public float weight_1_offset_radians;
        public float weight_2_offset_radians;
        public Std.HeaderMsg header;

        public BallastAnglesMsg()
        {
            this.weight_1_offset_radians = 0.0f;
            this.weight_2_offset_radians = 0.0f;
            this.header = new Std.HeaderMsg();
        }

        public BallastAnglesMsg(float weight_1_offset_radians, float weight_2_offset_radians, Std.HeaderMsg header)
        {
            this.weight_1_offset_radians = weight_1_offset_radians;
            this.weight_2_offset_radians = weight_2_offset_radians;
            this.header = header;
        }

        public static BallastAnglesMsg Deserialize(MessageDeserializer deserializer) => new BallastAnglesMsg(deserializer);

        private BallastAnglesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.weight_1_offset_radians);
            deserializer.Read(out this.weight_2_offset_radians);
            this.header = Std.HeaderMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.weight_1_offset_radians);
            serializer.Write(this.weight_2_offset_radians);
            serializer.Write(this.header);
        }

        public override string ToString()
        {
            return "BallastAnglesMsg: " +
            "\nweight_1_offset_radians: " + weight_1_offset_radians.ToString() +
            "\nweight_2_offset_radians: " + weight_2_offset_radians.ToString() +
            "\nheader: " + header.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
