//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class CircuitStatusStampedArrayMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/CircuitStatusStampedArray";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Uavcan CircuitStatus
        // 
        public CircuitStatusStampedMsg[] array;

        public CircuitStatusStampedArrayMsg()
        {
            this.array = new CircuitStatusStampedMsg[0];
        }

        public CircuitStatusStampedArrayMsg(CircuitStatusStampedMsg[] array)
        {
            this.array = array;
        }

        public static CircuitStatusStampedArrayMsg Deserialize(MessageDeserializer deserializer) => new CircuitStatusStampedArrayMsg(deserializer);

        private CircuitStatusStampedArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.array, CircuitStatusStampedMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.array);
            serializer.Write(this.array);
        }

        public override string ToString()
        {
            return "CircuitStatusStampedArrayMsg: " +
            "\narray: " + System.String.Join(", ", array.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
