//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class CTPMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/CTP";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double conductivity;
        //  [mS/cm]
        public double temperature;
        //  [deg C]
        public double pressure;
        //  [bar]

        public CTPMsg()
        {
            this.header = new Std.HeaderMsg();
            this.conductivity = 0.0;
            this.temperature = 0.0;
            this.pressure = 0.0;
        }

        public CTPMsg(Std.HeaderMsg header, double conductivity, double temperature, double pressure)
        {
            this.header = header;
            this.conductivity = conductivity;
            this.temperature = temperature;
            this.pressure = pressure;
        }

        public static CTPMsg Deserialize(MessageDeserializer deserializer) => new CTPMsg(deserializer);

        private CTPMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.conductivity);
            deserializer.Read(out this.temperature);
            deserializer.Read(out this.pressure);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.conductivity);
            serializer.Write(this.temperature);
            serializer.Write(this.pressure);
        }

        public override string ToString()
        {
            return "CTPMsg: " +
            "\nheader: " + header.ToString() +
            "\nconductivity: " + conductivity.ToString() +
            "\ntemperature: " + temperature.ToString() +
            "\npressure: " + pressure.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
