//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class LightCommandArrayMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/LightCommandArray";
        public override string RosMessageName => k_RosMessageName;

        // 
        //  Light command
        // 
        public LightCommandMsg[] array;

        public LightCommandArrayMsg()
        {
            this.array = new LightCommandMsg[0];
        }

        public LightCommandArrayMsg(LightCommandMsg[] array)
        {
            this.array = array;
        }

        public static LightCommandArrayMsg Deserialize(MessageDeserializer deserializer) => new LightCommandArrayMsg(deserializer);

        private LightCommandArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.array, LightCommandMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.array);
            serializer.Write(this.array);
        }

        public override string ToString()
        {
            return "LightCommandArrayMsg: " +
            "\narray: " + System.String.Join(", ", array.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
