//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Sam
{
    [Serializable]
    public class TopicsMsg : Message
    {
        public const string k_RosMessageName = "sam_msgs/Topics";
        public override string RosMessageName => k_RosMessageName;

        //  This is a file that defines all the topics of sam.
        //  The goal is to have one location that all cpp/py scripts
        //  can easily access and thus avoid having 100 parameters for topics all
        //  over the place, repeated for all subs/pubs...
        //  It is assumed that the nodes will namespace as needed.
        // ###################
        //  Actuator commands
        // ###################
        public const string VBS_CMD_TOPIC = "'core/vbs_cmd'";
        public const string LCG_CMD_TOPIC = "'core/lcg_cmd'";
        public const string THRUSTER1_CMD_TOPIC = "'core/thruster1_cmd'";
        public const string THRUSTER2_CMD_TOPIC = "'core/thruster2_cmd'";
        public const string THRUST_VECTOR_CMD_TOPIC = "'core/thrust_vector_cmd'";

        public TopicsMsg()
        {
        }
        public static TopicsMsg Deserialize(MessageDeserializer deserializer) => new TopicsMsg(deserializer);

        private TopicsMsg(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "TopicsMsg: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
