//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Smarc
{
    [Serializable]
    public class CommsMessageMsg : Message
    {
        public const string k_RosMessageName = "smarc_msgs/CommsMessage";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public string source_ns;
        public string target_ns;
        public string data;

        public CommsMessageMsg()
        {
            this.header = new Std.HeaderMsg();
            this.source_ns = "";
            this.target_ns = "";
            this.data = "";
        }

        public CommsMessageMsg(Std.HeaderMsg header, string source_ns, string target_ns, string data)
        {
            this.header = header;
            this.source_ns = source_ns;
            this.target_ns = target_ns;
            this.data = data;
        }

        public static CommsMessageMsg Deserialize(MessageDeserializer deserializer) => new CommsMessageMsg(deserializer);

        private CommsMessageMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.source_ns);
            deserializer.Read(out this.target_ns);
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.source_ns);
            serializer.Write(this.target_ns);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "CommsMessageMsg: " +
            "\nheader: " + header.ToString() +
            "\nsource_ns: " + source_ns.ToString() +
            "\ntarget_ns: " + target_ns.ToString() +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
