//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Smarc
{
    [Serializable]
    public class CTDMsg : Message
    {
        public const string k_RosMessageName = "smarc_msgs/CTD";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double conductivity;
        //  [mS/cm]
        public double temperature;
        //  [deg C]
        public double depth;
        //  [m]

        public CTDMsg()
        {
            this.header = new Std.HeaderMsg();
            this.conductivity = 0.0;
            this.temperature = 0.0;
            this.depth = 0.0;
        }

        public CTDMsg(Std.HeaderMsg header, double conductivity, double temperature, double depth)
        {
            this.header = header;
            this.conductivity = conductivity;
            this.temperature = temperature;
            this.depth = depth;
        }

        public static CTDMsg Deserialize(MessageDeserializer deserializer) => new CTDMsg(deserializer);

        private CTDMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.conductivity);
            deserializer.Read(out this.temperature);
            deserializer.Read(out this.depth);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.conductivity);
            serializer.Write(this.temperature);
            serializer.Write(this.depth);
        }

        public override string ToString()
        {
            return "CTDMsg: " +
            "\nheader: " + header.ToString() +
            "\nconductivity: " + conductivity.ToString() +
            "\ntemperature: " + temperature.ToString() +
            "\ndepth: " + depth.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
