//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Smarc
{
    [Serializable]
    public class DualThrusterRPMMsg : Message
    {
        public const string k_RosMessageName = "smarc_msgs/DualThrusterRPM";
        public override string RosMessageName => k_RosMessageName;

        public ThrusterRPMMsg thruster_front;
        public ThrusterRPMMsg thruster_back;

        public DualThrusterRPMMsg()
        {
            this.thruster_front = new ThrusterRPMMsg();
            this.thruster_back = new ThrusterRPMMsg();
        }

        public DualThrusterRPMMsg(ThrusterRPMMsg thruster_front, ThrusterRPMMsg thruster_back)
        {
            this.thruster_front = thruster_front;
            this.thruster_back = thruster_back;
        }

        public static DualThrusterRPMMsg Deserialize(MessageDeserializer deserializer) => new DualThrusterRPMMsg(deserializer);

        private DualThrusterRPMMsg(MessageDeserializer deserializer)
        {
            this.thruster_front = ThrusterRPMMsg.Deserialize(deserializer);
            this.thruster_back = ThrusterRPMMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.thruster_front);
            serializer.Write(this.thruster_back);
        }

        public override string ToString()
        {
            return "DualThrusterRPMMsg: " +
            "\nthruster_front: " + thruster_front.ToString() +
            "\nthruster_back: " + thruster_back.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
