//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Smarc
{
    [Serializable]
    public class DualThrusterFeedbackMsg : Message
    {
        public const string k_RosMessageName = "smarc_msgs/DualThrusterFeedback";
        public override string RosMessageName => k_RosMessageName;

        public ThrusterFeedbackMsg thruster_front;
        public ThrusterFeedbackMsg thruster_back;

        public DualThrusterFeedbackMsg()
        {
            this.thruster_front = new ThrusterFeedbackMsg();
            this.thruster_back = new ThrusterFeedbackMsg();
        }

        public DualThrusterFeedbackMsg(ThrusterFeedbackMsg thruster_front, ThrusterFeedbackMsg thruster_back)
        {
            this.thruster_front = thruster_front;
            this.thruster_back = thruster_back;
        }

        public static DualThrusterFeedbackMsg Deserialize(MessageDeserializer deserializer) => new DualThrusterFeedbackMsg(deserializer);

        private DualThrusterFeedbackMsg(MessageDeserializer deserializer)
        {
            this.thruster_front = ThrusterFeedbackMsg.Deserialize(deserializer);
            this.thruster_back = ThrusterFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.thruster_front);
            serializer.Write(this.thruster_back);
        }

        public override string ToString()
        {
            return "DualThrusterFeedbackMsg: " +
            "\nthruster_front: " + thruster_front.ToString() +
            "\nthruster_back: " + thruster_back.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
