//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Smarc
{
    [Serializable]
    public class LatLonStampedMsg : Message
    {
        public const string k_RosMessageName = "smarc_msgs/LatLonStamped";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double latitude;
        public double longitude;

        public LatLonStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.latitude = 0.0;
            this.longitude = 0.0;
        }

        public LatLonStampedMsg(Std.HeaderMsg header, double latitude, double longitude)
        {
            this.header = header;
            this.latitude = latitude;
            this.longitude = longitude;
        }

        public static LatLonStampedMsg Deserialize(MessageDeserializer deserializer) => new LatLonStampedMsg(deserializer);

        private LatLonStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.longitude);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.latitude);
            serializer.Write(this.longitude);
        }

        public override string ToString()
        {
            return "LatLonStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\nlatitude: " + latitude.ToString() +
            "\nlongitude: " + longitude.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
