//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Smarc
{
    [Serializable]
    public class StringArrayMsg : Message
    {
        public const string k_RosMessageName = "smarc_msgs/StringArray";
        public override string RosMessageName => k_RosMessageName;

        public string[] string_array;

        public StringArrayMsg()
        {
            this.string_array = new string[0];
        }

        public StringArrayMsg(string[] string_array)
        {
            this.string_array = string_array;
        }

        public static StringArrayMsg Deserialize(MessageDeserializer deserializer) => new StringArrayMsg(deserializer);

        private StringArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.string_array, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.string_array);
            serializer.Write(this.string_array);
        }

        public override string ToString()
        {
            return "StringArrayMsg: " +
            "\nstring_array: " + System.String.Join(", ", string_array.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
